# Generated by Django 4.2.6 on 2023-10-27 16:03

from django.db import migrations, models

def add_initial_subjects(apps, schema_editor):
    Subject = apps.get_model('teacher', 'Subject')

    initial_subject_names = ['Mathematics', 'Physics', 'Chemistry', 'Biology', 'History','Computer science','English', 'Arabic','Geography']

    for subject_name in initial_subject_names:
        Subject.objects.get_or_create(sub_name=subject_name)
        

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='teacher/csv/')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_first_name', models.CharField(max_length=255)),
                ('teacher_last_name', models.CharField(max_length=255)),
                ('teacher_email', models.EmailField(max_length=100, unique=True)),
                ('teacher_phone_number', models.CharField(max_length=12)),
                ('teacher_room', models.CharField(max_length=10)),
                ('teacher_profile_pic', models.ImageField(blank=True, null=True, upload_to='teacher/profile_pic/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_subjects', models.ManyToManyField(to='teacher.subject')),
            ],
        ),
        migrations.RunPython(add_initial_subjects),
    ]
