# Generated by Django 4.2.6 on 2023-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_profile_pic',
            new_name='tchr_profile_pic',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='room',
            new_name='tchr_room',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='tchr_subjects',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='tchr_email',
            field=models.EmailField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='tchr_first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='tchr_last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='tchr_phone_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
