# Generated by Django 4.2.6 on 2023-10-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_tchr_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tchr_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.room'),
        ),
    ]
