# Generated by Django 4.2.6 on 2023-10-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_teacher_tchr_subjects_teacher_tchr_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tchr_room',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
