# Generated by Django 4.2.6 on 2023-10-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_teacher_tchr_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='tchr_email',
            new_name='teacher_email',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tchr_first_name',
            new_name='teacher_first_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tchr_last_name',
            new_name='teacher_last_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tchr_phone_number',
            new_name='teacher_phone_number',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tchr_profile_pic',
            new_name='teacher_profile_pic',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tchr_room',
            new_name='teacher_room',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tchr_subjects',
            new_name='teacher_subjects',
        ),
    ]
