# Generated by Django 4.2.6 on 2023-10-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_subjects',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_subjects',
            field=models.ManyToManyField(to='teacher.subject'),
        ),
    ]
