# Generated by Django 4.2.6 on 2023-10-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_remove_teacher_teacher_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
